
version: 2
jobs:
  build-only:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Generate Dependencies
          command: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Build & Test
          command: ./gradlew test

      - store_test_results:
          path: build/test-results

  build-deploy:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Generate Dependencies
          command: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Build & Test
          command: ./gradlew test

      - run:
          name: Publish
          command: ./gradlew -PossrhUsername=$OSSRH_USER -PossrhPassword=$OSSRH_PASS publishMavenJavaPublicationToMavenRepository

      - run:
          name: Update Documentation
          command: ./gradlew gitPublishPush

      - store_test_results:
          path: build/test-results

workflows:
  version: 2
  build:
    jobs:
      - build-only:
          filters:
            branches:
              ignore:
                - master
                - develop
      - build-deploy:
          filters:
            branches:
              only:
                - master
                - develop
