name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build & Test
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: jdk8-build-test
        arguments: build

    - name: Updload Reports
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: build/reports


  publish:
    runs-on: ubuntu-latest

    needs: [build-test]

    if: github.event.pull_request.merged || github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2

    - name: Build
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: jdk8-build-test
        arguments: build -x test

    - name: Publish Maven (Snapshot)
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: jdk8-build-test
        arguments: publishMavenRelease
        properties: |
          ossrhUsername=${{ secrets.OSSRH_USER }}
          ossrhPassword=${{ secrets.OSSRH_PASS }}

    - name: Publish Documentation
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        clean: false
        folder: build/javadoc
